export type CapabilityStatus = 'available' | 'requires-environment' | 'degraded' | 'placeholder'

export interface IpcChannelContract {
  capability: string
  channel: string
  renderer: string
  service: string
  preload: 'invoke' | 'on'
  ipc: string
  request: string
  response: string
  status: CapabilityStatus
  note: string
}

type ContractDefinition = readonly [
  capability: string,
  channel: string,
  renderer: string,
  service: string,
  ipc: string,
  request: string,
  response: string,
  status: CapabilityStatus,
  note: string,
]

function invoke(...definition: ContractDefinition): IpcChannelContract {
  const [capability, channel, renderer, service, ipc, request, response, status, note] = definition
  return {
    capability,
    channel,
    renderer,
    service,
    preload: 'invoke',
    ipc,
    request,
    response,
    status,
    note,
  }
}

function event(...definition: ContractDefinition): IpcChannelContract {
  return { ...invoke(...definition), preload: 'on' }
}

/**
 * Auditable Renderer -> Service -> Preload -> IPC contracts.
 *
 * This is intentionally exhaustive: every channel exposed by electron/preload.ts must have one
 * entry, including backend-only and placeholder capabilities. tests/ipcContractMatrix.test.ts
 * compares this list with the real preload allowlists and main-process registrations.
 */
export const IPC_CHANNEL_CONTRACTS: readonly IpcChannelContract[] = [
  // Local execution
  invoke(
    'local-code-runner',
    'run-code',
    'WorkspaceView / useWorkspaceData',
    'workspaceService.runCode',
    'registerRunnerIPC',
    '{ code, language, stdin?, executionMode?: local-controlled | strong-isolation }',
    'RunResult { stdout, stderr, exitCode, duration_ms, stage?, toolchain?, isolation? }',
    'requires-environment',
    'Local-controlled execution uses a disposable utility process. Windows adds a fail-closed Job Object; POSIX uses best-effort ulimit/process-group cleanup. Both remain same-user local execution, not a sandbox. strong-isolation routes supported languages through Docker (pinned digests, --network none, --read-only, cap-drop ALL, non-root, resource limits, --cidfile + docker rm -f on abort) and fails closed if Docker/images are unavailable — never silent fallback to local. SQL is not supported under strong isolation (in-memory SQLite utility is a separate local-controlled boundary). Missing toolchains return install hints instead of raw ENOENT.',
  ),
  invoke(
    'local-toolchain-detect',
    'runner-detect-toolchains',
    'WorkspaceView status bar',
    'workspaceService.detectToolchains',
    'registerRunnerIPC',
    '{ force?: boolean }',
    'ToolchainReport { tools, isolation, platform, detectedAt }',
    'requires-environment',
    'Probes python/node/gcc/g++/dotnet-or-csc/mcs and Docker strong-isolation images asynchronously (cached), and marks SQL as built-in. UI must show ready/degraded/missing and strongIsolationAvailable honestly.',
  ),
  invoke(
    'local-runner-isolation-info',
    'runner-isolation-info',
    'WorkspaceView status bar',
    'workspaceService.getRunnerIsolationInfo',
    'registerRunnerIPC',
    'void',
    'IsolationInfo { mode: local-controlled | strong-isolation, label, description, strongIsolationAvailable, strongIsolationReason }',
    'degraded',
    'Always discloses local-controlled non-sandbox boundaries. strongIsolationAvailable is true only after a cached Docker probe finds pinned images; getIsolationInfo never blocks the UI on Docker. Job containment alone does not block same-user filesystem or network access.',
  ),

  // Settings and provider configuration
  invoke(
    'setting-read',
    'db-get-setting',
    'appStore / onboardingStore / settings UI',
    'settingsService.getSetting',
    'registerDatabaseIPC',
    'key: string',
    'string | null',
    'available',
    'Reads a bounded setting value from SQLite.',
  ),
  invoke(
    'setting-write',
    'db-set-setting',
    'appStore / onboardingStore / settings UI',
    'settingsService.setSetting',
    'registerDatabaseIPC',
    'key: string, value: string',
    'void',
    'available',
    'Writes a bounded setting value to SQLite.',
  ),
  invoke(
    'ai-config-list',
    'db-get-ai-configs',
    'SettingsView / settingsStore',
    'settingsService.getAIConfigs',
    'registerDatabaseIPC',
    'none',
    'AIConfig[] with masked credentials',
    'available',
    'Lists persisted provider configurations without exposing stored plaintext secrets.',
  ),
  invoke(
    'ai-config-save',
    'db-save-ai-config',
    'SettingsView / settingsStore',
    'settingsService.saveAIConfig',
    'registerDatabaseIPC',
    'AIConfig',
    'saved config id',
    'available',
    'Validates provider URLs and stores the API key through encrypted credential storage.',
  ),
  invoke(
    'ai-config-delete',
    'db-delete-ai-config',
    'SettingsView / settingsStore',
    'settingsService.deleteAIConfig',
    'registerDatabaseIPC',
    'id: number',
    'void',
    'available',
    'Deletes one persisted provider configuration.',
  ),
  invoke(
    'ai-config-default',
    'db-get-default-ai-config',
    'not connected',
    'settingsService.getDefaultAIConfig',
    'registerDatabaseIPC',
    'none',
    'AIConfig | null with masked credential',
    'degraded',
    'The handler and service wrapper are real, but no renderer entry currently calls them.',
  ),
  invoke(
    'ai-model-discovery',
    'ai-fetch-models',
    'SettingsView',
    'settingsService.fetchModels',
    'registerDatabaseIPC',
    '{ api_key, base_url, config_id? }',
    'model id string[]',
    'requires-environment',
    'Requires a configured reachable provider and valid credentials.',
  ),
  invoke(
    'platform-information',
    'platform-info',
    'SettingsView',
    'settingsService.getPlatformInfo',
    'electron/main.ts',
    'none',
    'PlatformInfo',
    'available',
    'Returns runtime, operating-system, architecture, and application versions.',
  ),
  invoke(
    'app-close-flush-response',
    'app-close-flush-complete',
    'App',
    'appCloseLifecycle.bindAppCloseLifecycle',
    'electron/main.ts',
    '{ requestId, ok, error?, recoveryAvailable? }',
    '{ accepted: boolean }',
    'available',
    'Completes the bounded close handshake after registered renderer persistence handlers settle.',
  ),

  // AI chat and persisted conversation data
  invoke(
    'ai-chat-stream-start',
    'ai-chat',
    'ChatView / chatStore',
    'aiService.sendMessage',
    'registerAIIPC',
    '{ messages, configId?, requestId?, sessionId?, memory and RAG options }',
    '{ success, requestId, content }',
    'requires-environment',
    'Requires a configured reachable provider; chunks and completion are emitted as events.',
  ),
  invoke(
    'ai-chat-cancel',
    'ai-chat-cancel',
    'AITutorView Agent controls',
    'agentService.cancelAIRequest',
    'registerAIIPC',
    'requestId: string',
    '{ cancelled: boolean }',
    'available',
    'Aborts only the matching in-flight AI request; unknown or already-finished IDs return cancelled=false.',
  ),
  invoke(
    'agent-tool-capabilities',
    'agent-tools-list',
    'AITutorView Agent tool selector',
    'agentService.getAgentTools',
    'registerAgentIPC',
    'none',
    'AgentToolDefinition[]',
    'requires-environment',
    'The Electron main process is authoritative for the whitelist. Knowledge search is read-only; strong code execution is exposed only when Docker isolation is ready and always requires per-call approval.',
  ),
  invoke(
    'agent-run-history',
    'agent-runs-list',
    'AITutorView Agent history',
    'agentService.getAgentRuns',
    'registerAgentIPC',
    'limit?: number',
    'AgentRunRecord[]',
    'available',
    'Reads durable Agent run, tool-call, and approval state from SQLite.',
  ),
  invoke(
    'agent-audit-history',
    'agent-audit-list',
    'AITutorView Agent audit panel',
    'agentService.getAgentAudit',
    'registerAgentIPC',
    'runId, limit?',
    'AgentAuditEvent[]',
    'available',
    'Returns append-only SQLite audit events for one Agent run.',
  ),
  invoke(
    'agent-run-create',
    'agent-run-create',
    'AITutorView Agent form',
    'agentService.createAgentRun',
    'registerAgentIPC',
    'CreateAgentRunInput { goal, context?, tools[] }',
    'AgentRunRecord',
    'available',
    'Validates the main-process whitelist, stores hashed input summaries, executes only approval-free tools, and holds gated tools in needsApproval.',
  ),
  invoke(
    'agent-tool-approve',
    'agent-run-approve',
    'AITutorView approval panel',
    'agentService.approveAgentTool',
    'registerAgentIPC',
    '{ runId, toolCallId, note? }',
    'AgentRunRecord',
    'requires-environment',
    'Approves one pending tool call for one run. Approvals expire after ten minutes and cannot authorize local fallback.',
  ),
  invoke(
    'agent-tool-reject',
    'agent-run-reject',
    'AITutorView approval panel',
    'agentService.rejectAgentTool',
    'registerAgentIPC',
    '{ runId, toolCallId, note? }',
    'AgentRunRecord',
    'available',
    'Rejects one pending tool call, records the decision, and cancels the run.',
  ),
  invoke(
    'agent-run-cancel',
    'agent-run-cancel',
    'AITutorView Agent controls',
    'agentService.cancelAgentRun',
    'registerAgentIPC',
    '{ runId, note? }',
    'AgentRunRecord',
    'available',
    'Marks pending/running calls cancelled, aborts the active Agent controller, and discards late tool results. Docker retains its own bounded cleanup guarantee.',
  ),
  invoke(
    'agent-model-started',
    'agent-run-model-started',
    'AITutorView Agent dispatcher',
    'agentService.markAgentModelStarted',
    'registerAgentIPC',
    '{ runId, requestId? }',
    'AgentRunRecord',
    'available',
    'Records the transition from verified tool evidence to model synthesis.',
  ),
  invoke(
    'agent-run-complete',
    'agent-run-complete',
    'AITutorView Agent dispatcher',
    'agentService.completeAgentRun',
    'registerAgentIPC',
    '{ runId }',
    'AgentRunRecord',
    'available',
    'Marks a non-terminal run complete only after the model request settles successfully.',
  ),
  invoke(
    'agent-run-fail',
    'agent-run-fail',
    'AITutorView Agent dispatcher',
    'agentService.failAgentRun',
    'registerAgentIPC',
    '{ runId, note? }',
    'AgentRunRecord',
    'available',
    'Records model or orchestration failure without overwriting an already cancelled or terminal run.',
  ),
  invoke(
    'chat-session-list',
    'chat-sessions-list',
    'ChatView / chatStore',
    'aiService.getSessions',
    'registerChatIPC',
    'none',
    'ChatSession[]',
    'available',
    'Lists locally persisted chat sessions.',
  ),
  invoke(
    'chat-session-create',
    'chat-session-create',
    'ChatView / chatStore',
    'aiService.createSession',
    'registerChatIPC',
    '{ id, title?, system_prompt? }',
    'ChatSession',
    'available',
    'Creates a locally persisted chat session.',
  ),
  invoke(
    'chat-session-update',
    'chat-session-update',
    'ChatView / chatStore',
    'chatStore direct IPC',
    'registerChatIPC',
    'id: string, { title?, system_prompt? }',
    'void',
    'available',
    'Updates a session title or system prompt.',
  ),
  invoke(
    'chat-session-delete',
    'chat-session-delete',
    'ChatView / chatStore',
    'aiService.deleteSession',
    'registerChatIPC',
    'id: string',
    'void',
    'available',
    'Deletes a session and its persisted messages.',
  ),
  invoke(
    'chat-message-load',
    'chat-messages-load',
    'ChatView / chatStore',
    'aiService.loadMessages',
    'registerChatIPC',
    'sessionId: string',
    'ChatMessage[]',
    'available',
    'Loads messages for one session.',
  ),
  invoke(
    'chat-message-save',
    'chat-message-save',
    'ChatView / chatStore',
    'aiService.saveMessage',
    'registerChatIPC',
    '{ session_id, role, content, model? }',
    'saved message id',
    'available',
    'Persists one chat message.',
  ),
  invoke(
    'chat-preset-list',
    'chat-presets-list',
    'ChatView / chatStore',
    'aiService.getPresets',
    'registerChatIPC',
    'none',
    'PromptPreset[]',
    'available',
    'Lists locally persisted prompt presets.',
  ),
  invoke(
    'chat-preset-save',
    'chat-preset-save',
    'not connected',
    'not connected (handler only)',
    'registerChatIPC',
    '{ id?, name, prompt }',
    'void',
    'degraded',
    'The handler is real but no renderer entry currently calls it.',
  ),
  invoke(
    'chat-preset-delete',
    'chat-preset-delete',
    'not connected',
    'not connected (handler only)',
    'registerChatIPC',
    'id: number',
    'void',
    'degraded',
    'The handler is real but no renderer entry currently calls it.',
  ),
  invoke(
    'chat-memory-list',
    'chat-memories-list',
    'MemorySettings / chatStore',
    'memoryService.listMemories',
    'registerChatIPC',
    'search?: string',
    'Memory[]',
    'available',
    'Lists or filters local conversation memories.',
  ),
  invoke(
    'chat-memory-save',
    'chat-memory-save',
    'MemorySettings / chatStore',
    'memoryService.saveMemory',
    'registerChatIPC',
    'MemoryInput',
    'Memory',
    'available',
    'Creates or updates a local memory record.',
  ),
  invoke(
    'chat-memory-delete',
    'chat-memory-delete',
    'MemorySettings / chatStore',
    'memoryService.deleteMemory',
    'registerChatIPC',
    'id: number',
    'void',
    'available',
    'Deletes one local memory record.',
  ),
  invoke(
    'chat-memory-capture',
    'chat-memory-capture',
    'ChatView / chatStore',
    'aiService.captureMemory',
    'registerChatIPC',
    '{ content, session_id? }',
    'Memory[]',
    'available',
    'Uses deterministic local extraction to capture a memory candidate.',
  ),
  invoke(
    'chat-context-preview',
    'chat-context-preview',
    'MemorySettings',
    'memoryService.previewContext',
    'registerChatIPC',
    '{ query?, includeMemories?, memoryCategories? }',
    '{ memories: Memory[] }',
    'available',
    'Previews the local memories that would be injected into a chat request.',
  ),
  invoke(
    'chat-memory-batch',
    'chat-memories-batch',
    'MemorySettings',
    'memoryService.batchMemories',
    'registerChatIPC',
    '{ ids, action }',
    '{ affected: number }',
    'available',
    'Applies an enable, disable, pin, unpin, or delete action to local memories.',
  ),
  invoke(
    'chat-memory-ai-extract',
    'chat-memory-extract',
    'ChatView / MemorySettings',
    'memoryService.extractMemory',
    'registerChatIPC',
    '{ content, configId?, sessionId? }',
    'Memory[]',
    'requires-environment',
    'The AI-enhanced extraction path requires a configured reachable provider.',
  ),

  // Problems, mistakes, and review
  invoke(
    'problem-list',
    'problems-list',
    'ProblemListView / problemStore',
    'workspaceService.getProblems',
    'registerProblemsIPC',
    'problem filters?',
    'Problem[]',
    'available',
    'Lists local problems with bounded optional filters.',
  ),
  invoke(
    'problem-detail',
    'problems-get',
    'ProblemDetailView / problemStore',
    'workspaceService.getProblem',
    'registerProblemsIPC',
    'id: number',
    'Problem | undefined',
    'available',
    'Loads one local problem.',
  ),
  invoke(
    'problem-submit',
    'problems-submit',
    'WorkspaceView / problemStore',
    'workspaceService.submitToProblem',
    'registerProblemsIPC',
    '{ problemId, code, language }',
    'ProblemSubmitResponse',
    'requires-environment',
    'Judging uses the local code runner and therefore depends on the selected toolchain.',
  ),
  invoke(
    'problem-submission-history',
    'problems-submissions',
    'ProblemDetailView',
    'workspaceService.getSubmissions',
    'registerProblemsIPC',
    'problemId: number',
    'Submission[]',
    'available',
    'Lists persisted submissions for one problem.',
  ),
  invoke(
    'mistake-list',
    'mistakes-list',
    'ReviewView',
    'reviewService.getMistakes',
    'registerMistakesIPC',
    'none',
    'Mistake[]',
    'available',
    'Lists locally persisted mistake records.',
  ),
  invoke(
    'mistake-detail',
    'mistakes-get',
    'ReviewView',
    'reviewService.getMistake',
    'registerMistakesIPC',
    'id: string | number',
    'MistakeDetail | undefined',
    'available',
    'Loads one mistake record.',
  ),
  invoke(
    'mistake-analysis-update',
    'mistakes-update-analysis',
    'ReviewView',
    'reviewService.updateAnalysis',
    'registerMistakesIPC',
    'id: string | number, analysis: string',
    'void',
    'available',
    'Updates the local analysis text for a mistake.',
  ),
  invoke(
    'mistake-delete',
    'mistakes-delete',
    'ReviewView',
    'reviewService.deleteMistake',
    'registerMistakesIPC',
    'id: string | number',
    'void',
    'available',
    'Deletes one local mistake record.',
  ),
  invoke(
    'review-due-list',
    'review-due',
    'HomeView / PracticeView / ReviewView',
    'practiceService.getReviewDue / reviewService.getDueReviews',
    'registerReviewIPC',
    'none',
    'ReviewScheduleRow[]',
    'available',
    'Returns due spaced-repetition items.',
  ),
  invoke(
    'review-update',
    'review-update',
    'PracticeView / ReviewView',
    'practiceService.updateReview / reviewService.updateReview',
    'registerReviewIPC',
    '{ exercise_id, quality }',
    'updated ReviewScheduleRow',
    'available',
    'Updates an SM-2 review schedule from a bounded quality score.',
  ),
  invoke(
    'review-statistics',
    'review-stats',
    'ReviewView',
    'reviewService.getReviewStats',
    'registerReviewIPC',
    'none',
    '{ totalDue, completedToday, mastered }',
    'available',
    'Returns aggregate local review statistics.',
  ),
  invoke(
    'review-schedule-detail',
    'review-schedule',
    'not connected',
    'not connected (handler only)',
    'registerReviewIPC',
    'exerciseId: string',
    'ReviewScheduleRow | undefined',
    'degraded',
    'The handler is real but no renderer entry currently calls it.',
  ),

  // Knowledge base and resource packs
  invoke(
    'knowledge-upload',
    'knowledge-upload',
    'KnowledgeView / useKnowledgeData',
    'knowledgeService.uploadDocument',
    'registerRAGIPC',
    'none (native file dialog)',
    'imported filename[] | null',
    'available',
    'Imports selected text, Markdown, or PDF documents into SQLite.',
  ),
  invoke(
    'knowledge-list',
    'knowledge-list',
    'KnowledgeView / useKnowledgeData',
    'knowledgeService.getDocuments',
    'registerRAGIPC',
    'none',
    'KnowledgeDoc[]',
    'available',
    'Lists imported knowledge documents.',
  ),
  invoke(
    'knowledge-detail',
    'knowledge-get',
    'KnowledgeView / useKnowledgeData',
    'knowledgeService.getDocument',
    'registerRAGIPC',
    'id: number',
    'KnowledgeDocDetail | null',
    'available',
    'Loads one imported document including its content.',
  ),
  invoke(
    'knowledge-link-audit',
    'knowledge-link-audit',
    'KnowledgeView (offline link status)',
    'knowledgeService.getDocumentLinkAudit',
    'registerRAGIPC',
    'docId: number',
    'KnowledgeLinkAuditRecord[]',
    'available',
    'Returns persisted per-link resolution and HTTP audit status without issuing network requests.',
  ),
  invoke(
    'knowledge-delete',
    'knowledge-delete',
    'KnowledgeView / useKnowledgeData',
    'knowledgeService.deleteDocument',
    'registerRAGIPC',
    'id: number',
    'void',
    'available',
    'Deletes a document and its chunks.',
  ),
  invoke(
    'knowledge-keyword-search',
    'knowledge-search',
    'KnowledgeView / useKnowledgeData',
    'knowledgeService.searchDocuments',
    'registerRAGIPC',
    'query: string',
    'KnowledgeSearchResponse { query, results, retrieval }',
    'available',
    'Uses SQLite FTS5 BM25 + trigram recall, local n-gram similarity, terminology expansion, and reciprocal-rank fusion. Falls back to bounded LIKE without hiding degradation.',
  ),
  invoke(
    'knowledge-retrieval-status',
    'knowledge-retrieval-status',
    'KnowledgeView / useKnowledgeData',
    'knowledgeService.getRetrievalStatus',
    'registerRAGIPC',
    'none',
    'KnowledgeRetrievalStatus',
    'available',
    'Reports the active lexical/semantic backends, index counts, and any degradation reason.',
  ),
  invoke(
    'knowledge-semantic-search',
    'knowledge-semantic-search',
    'KnowledgeView / knowledgeStore',
    'knowledgeService.semanticSearch',
    'registerRAGIPC',
    'query: string',
    'SemanticSearchResult[]',
    'available',
    'Returns the local semantic-approximation ranking from trigram FTS and deterministic n-gram similarity; it does not claim model embeddings.',
  ),
  invoke(
    'knowledge-summary',
    'knowledge-summarize',
    'KnowledgeView / knowledgeStore',
    'knowledgeStore.summarizeResults / knowledgeService.summarizeDocuments',
    'registerRAGIPC',
    'query: string',
    'KnowledgeSummary { summary, keyConcepts }',
    'degraded',
    'Produces a deterministic keyword-based fallback summary rather than an AI summary.',
  ),
  invoke(
    'knowledge-concept-graph',
    'knowledge-concept-graph',
    'KnowledgeView / knowledgeStore',
    'knowledgeStore direct IPC',
    'registerRAGIPC',
    'none',
    '{ nodes: [], edges: [] }',
    'placeholder',
    'The handler always returns an empty graph.',
  ),
  invoke(
    'knowledge-concept-detail',
    'knowledge-concept-detail',
    'KnowledgeView / knowledgeStore',
    'knowledgeStore direct IPC',
    'registerRAGIPC',
    'conceptId: string',
    'placeholder concept detail',
    'placeholder',
    'The handler returns a synthetic concept with empty document and relation lists.',
  ),
  invoke(
    'knowledge-auto-tag',
    'knowledge-auto-tag',
    'KnowledgeView / knowledgeStore',
    'knowledgeStore direct IPC',
    'registerRAGIPC',
    'docId: number',
    '[]',
    'placeholder',
    'The handler always returns an empty tag suggestion list.',
  ),
  invoke(
    'knowledge-tag-list',
    'knowledge-tags',
    'KnowledgeView / knowledgeStore',
    'knowledgeStore direct IPC',
    'registerRAGIPC',
    'none',
    '[]',
    'placeholder',
    'The handler always returns an empty tag list.',
  ),
  invoke(
    'knowledge-documents-by-tag',
    'knowledge-tag-documents',
    'KnowledgeView / knowledgeStore',
    'knowledgeStore direct IPC',
    'registerRAGIPC',
    'tag: string',
    '[]',
    'placeholder',
    'The handler validates a tag but always returns an empty document list.',
  ),
  invoke(
    'knowledge-rag-context',
    'knowledge-rag-context',
    'ChatView / KnowledgeView',
    'knowledgeService.getRAGContext',
    'registerRAGIPC',
    'query?: string',
    'RAGContext',
    'degraded',
    'Knowledge chunks use hybrid retrieval and include auditable source labels; learning history and profile sections remain static fallbacks.',
  ),
  invoke(
    'resource-pack-import',
    'resource-pack-import',
    'KnowledgeView / useKnowledgeData',
    'knowledgeService.importResourcePack',
    'registerResourcePackIPC',
    '{ rootPath? }',
    'ResourcePackImportResult | null',
    'available',
    'Imports validated learning resources from a selected workspace directory.',
  ),

  // Analytics, home, and demo data
  invoke(
    'analytics-track',
    'analytics-track',
    'feature service callers',
    'analyticsService.track',
    'registerAnalyticsIPC',
    'eventType, eventData?',
    'void',
    'available',
    'Stores bounded analytics events locally; no telemetry is sent externally.',
  ),
  invoke(
    'analytics-event-list',
    'analytics-get-events',
    'HomeView',
    'homeService.getRecentActivity',
    'registerAnalyticsIPC',
    'filters?',
    'AnalyticsEvent[]',
    'available',
    'Returns filtered local analytics events.',
  ),
  invoke(
    'analytics-summary',
    'analytics-get-summary',
    'HomeView',
    'homeService.getAnalyticsSummary',
    'registerAnalyticsIPC',
    'days?: number',
    'AnalyticsSummary',
    'available',
    'Returns bounded aggregate activity counts.',
  ),
  invoke(
    'analytics-streak',
    'analytics-get-streak',
    'HomeView',
    'homeService.getStreakData',
    'registerAnalyticsIPC',
    'none',
    'consecutive day count',
    'available',
    'Calculates the current learning streak from local events.',
  ),
  invoke(
    'analytics-weekly-report',
    'analytics-get-weekly-report',
    'analytics UI',
    'analyticsService.getWeeklyReport',
    'registerAnalyticsIPC',
    'weekOffset?: number',
    'WeeklyReport',
    'available',
    'Returns a local weekly activity report.',
  ),
  invoke(
    'analytics-clear',
    'analytics-clear',
    'not connected',
    'not connected (handler only)',
    'registerAnalyticsIPC',
    'none',
    'void',
    'degraded',
    'The privacy handler is real but no renderer entry currently calls it.',
  ),
  invoke(
    'demo-data-load',
    'demo-load-data',
    'not connected',
    'not connected (handler only)',
    'registerDemoDataIPC',
    'none',
    'DemoLoadResult',
    'degraded',
    'The demo loader is implemented but is not connected to the renderer.',
  ),
  invoke(
    'home-overview',
    'home-get-overview',
    'HomeView',
    'homeService.getOverview',
    'registerHomeHandlers',
    'none',
    'HomeOverview',
    'available',
    'Returns the local home dashboard aggregate.',
  ),

  // Export, import, and diagnostics
  invoke(
    'data-export-dialog',
    'export-data',
    'SettingsView',
    'settingsService.exportData',
    'registerExportIPC',
    'ExportCategory[]',
    '{ success, filePath?, error? }',
    'available',
    'Exports selected categories through a native save dialog.',
  ),
  invoke(
    'data-import-dialog',
    'import-data',
    'SettingsView',
    'settingsService.importData',
    'registerExportIPC',
    'ImportOptions?',
    'ImportResult',
    'available',
    'Validates a portable JSON subset, creates a verified pre-import SQLite backup, and rolls the transaction back on any row error.',
  ),
  invoke(
    'data-export-counts',
    'export-get-counts',
    'not connected',
    'not connected (handler only)',
    'registerExportIPC',
    'none',
    'record counts by export category',
    'degraded',
    'The count endpoint is implemented but has no renderer entry.',
  ),
  invoke(
    'database-backup-list',
    'database-backups-list',
    'DataProtectionSettings',
    'maintenanceService.listDatabaseBackups',
    'registerMaintenanceIPC',
    'none',
    'DatabaseBackupListResult',
    'available',
    'Lists verified SQLite snapshots and manifest warnings without deleting any backup.',
  ),
  invoke(
    'database-backup-create',
    'database-backup-create',
    'DataProtectionSettings',
    'maintenanceService.createDatabaseBackup',
    'registerMaintenanceIPC',
    'none',
    'DatabaseBackupCreateResult',
    'available',
    'Flushes every renderer first, then creates a VACUUM INTO snapshot verified by quick_check and SHA-256. Fails closed if any window cannot persist.',
  ),
  invoke(
    'database-backup-open-directory',
    'database-backups-open-directory',
    'DataProtectionSettings',
    'maintenanceService.openDatabaseBackupDirectory',
    'registerMaintenanceIPC',
    'none',
    'OpenBackupDirectoryResult',
    'available',
    'Opens the application-owned backup directory; the renderer cannot provide an arbitrary path.',
  ),
  invoke(
    'recovery-layer-export',
    'recovery-layer-export',
    'DataProtectionSettings',
    'maintenanceService.exportRecoveryLayer',
    'registerMaintenanceIPC',
    'RecoveryLayerEntry[]',
    'RecoveryLayerExportResult',
    'available',
    'Exports only bounded codehelper migration-backup/corrupt localStorage entries through a native save dialog. It never restores or deletes them.',
  ),
  invoke(
    'system-capability-status',
    'system-capabilities-get',
    'CapabilityStatusSettings',
    'capabilityService.getSystemCapabilities',
    'registerCapabilitiesIPC',
    '{ force?: boolean }',
    'SystemCapabilityStatus',
    'requires-environment',
    'Aggregates live SQLite, backup, toolchain, Docker, knowledge, Agent, AI configuration, and runtime evidence. AI connectivity is not probed automatically.',
  ),
  invoke(
    'ipc-performance-stats',
    'perf-get-ipc-stats',
    'not connected',
    'not connected (diagnostic handler only)',
    'electron/main.ts',
    'none',
    'IPC performance statistics',
    'degraded',
    'The diagnostic endpoint is exposed but no renderer status page consumes it.',
  ),
  invoke(
    'external-link-open',
    'open-external',
    'KnowledgeView',
    'direct window.api.invoke',
    'electron/main.ts',
    'url: string (http/https only)',
    'void',
    'available',
    'Opens a validated external HTTP or HTTPS URL with the operating system.',
  ),

  // Lessons and practice
  invoke(
    'lesson-track-list',
    'lessons-list',
    'LearnView',
    'learnService.getTracks',
    'registerLessonsIPC',
    'none',
    'Track[]',
    'available',
    'Lists bundled lesson tracks.',
  ),
  invoke(
    'lesson-content',
    'lessons-get',
    'LessonView',
    'learnService.getLessonContent',
    'registerLessonsIPC',
    'lessonId: string',
    'Lesson',
    'available',
    'Loads one bundled lesson and its content.',
  ),
  invoke(
    'lesson-track-progress',
    'lessons-progress',
    'LearnView',
    'learnService.getLessonProgress',
    'registerLessonsIPC',
    'trackId: string',
    'LessonProgress[]',
    'available',
    'Lists persisted progress for a lesson track.',
  ),
  invoke(
    'lesson-mark-opened',
    'lessons-mark-opened',
    'LessonView',
    'learnService.markLessonOpened',
    'registerLessonsIPC',
    'lessonId: string, trackId: string',
    '{ ok: true }',
    'available',
    'Persists that a lesson was opened.',
  ),
  invoke(
    'lesson-mark-completed',
    'lessons-mark-completed',
    'LessonView',
    'learnService.markLessonCompleted',
    'registerLessonsIPC',
    'lessonId: string, trackId: string',
    '{ ok: true }',
    'available',
    'Persists lesson completion and related progress.',
  ),
  invoke(
    'lesson-note-read',
    'lessons-notes-get',
    'LessonView',
    'learnService.getLessonNote',
    'registerLessonsIPC',
    'lessonId: string',
    'note string',
    'available',
    'Loads the local note for one lesson.',
  ),
  invoke(
    'lesson-note-save',
    'lessons-notes-save',
    'LessonView',
    'learnService.saveLessonNote',
    'registerLessonsIPC',
    'lessonId: string, content: string',
    '{ ok: true }',
    'available',
    'Persists a bounded lesson note.',
  ),
  invoke(
    'lesson-search',
    'lessons-search',
    'LearnView',
    'learnService.searchLessons',
    'registerLessonsIPC',
    'query: string',
    'lesson id string[]',
    'available',
    'Searches bundled lesson metadata and content.',
  ),
  invoke(
    'lesson-progress-overview',
    'lesson-get-progress',
    'HomeView',
    'homeService.getDailyTasks',
    'registerLessonsIPC',
    'none',
    'lesson progress rows',
    'available',
    'Returns progress rows used by the home dashboard.',
  ),
  invoke(
    'exercise-list',
    'exercises-list',
    'PracticeView / usePracticeData',
    'practiceService.getExercises',
    'registerExercisesIPC',
    '{ track_id?, difficulty? }',
    'Exercise[]',
    'available',
    'Lists bundled exercises with optional filters.',
  ),
  invoke(
    'exercise-detail',
    'exercises-get',
    'PracticeView / usePracticeData',
    'practiceService.getExercise',
    'registerExercisesIPC',
    'id: string',
    'Exercise',
    'available',
    'Loads one bundled exercise.',
  ),
  invoke(
    'practice-draft-load',
    'exercises-draft-get',
    'usePracticeData.selectExercise',
    'practiceService.getDraft',
    'registerExercisesIPC',
    'exerciseId: string',
    'PracticeDraft | null',
    'available',
    'Loads a versioned SQLite draft and reconciles the local recovery snapshot.',
  ),
  invoke(
    'practice-draft-save',
    'exercises-draft-save',
    'DraftAutosaveCoordinator',
    'practiceService.saveDraft',
    'registerExercisesIPC',
    '{ exerciseId, code, language, baseRevision, title?: string | null }',
    'DraftMutationResult',
    'available',
    'Uses revision CAS; omitted titles are preserved, null explicitly clears, and retries are idempotent.',
  ),
  invoke(
    'practice-draft-clear',
    'exercises-draft-clear',
    'usePracticeData.clearCurrentDraft',
    'practiceService.clearDraft',
    'registerExercisesIPC',
    '{ exerciseId, baseRevision }',
    'DraftMutationResult',
    'available',
    'Writes a versioned tombstone instead of deleting unconditionally.',
  ),
  invoke(
    'exercise-evaluate',
    'exercises-evaluate',
    'PracticeView / usePracticeData',
    'practiceService.submitCode',
    'registerExercisesIPC',
    '{ exerciseId, code, language? }',
    '{ passed, score, feedback_lines, stdout, duration_sec }',
    'requires-environment',
    'Evaluation uses the local code runner and depends on the selected toolchain.',
  ),

  // Versioned editor workspace
  invoke(
    'editor-workspace-load',
    'editor-workspace-load',
    'EditorWorkspaceSynchronizer',
    'editorWorkspaceService.loadEditorWorkspace',
    'registerEditorWorkspaceIPC',
    '{ workspaceId }',
    'EditorWorkspaceRecord',
    'available',
    'Hydrates the editor store from SQLite; localStorage remains a crash-recovery fallback.',
  ),
  invoke(
    'editor-workspace-legacy-migration',
    'editor-workspace-migrate-legacy',
    'EditorWorkspaceSynchronizer startup migration',
    'editorWorkspaceService.migrateLegacyEditorWorkspace',
    'registerEditorWorkspaceIPC',
    'MigrateLegacyEditorWorkspaceInput',
    'MigrateLegacyEditorWorkspaceResult',
    'available',
    'Imports legacy local tabs transactionally and preserves conflicts as recovered copies.',
  ),
  invoke(
    'editor-tab-save',
    'editor-tab-save',
    'EditorWorkspaceSynchronizer',
    'editorWorkspaceService.saveEditorTab',
    'registerEditorWorkspaceIPC',
    'SaveEditorTabInput',
    'EditorTabMutationResult',
    'available',
    'Uses revision CAS, stable mutation IDs, and explicit conflict recovery.',
  ),
  invoke(
    'editor-view-state-save',
    'editor-tab-update-view-state',
    'EditorWorkspaceSynchronizer',
    'editorWorkspaceService.updateEditorTabViewState',
    'registerEditorWorkspaceIPC',
    'UpdateEditorTabViewStateInput',
    'EditorTabViewStateMutationResult',
    'available',
    'Persists the canonical tab cursor and scroll to SQLite; per-renderer pending view state remains protected by session recovery.',
  ),
  invoke(
    'editor-tab-close',
    'editor-tab-close',
    'EditorWorkspaceSynchronizer / tab controls',
    'editorWorkspaceService.closeEditorTab',
    'registerEditorWorkspaceIPC',
    'VersionedEditorTabMutationInput',
    'EditorTabMutationResult',
    'available',
    'Closes a tab with revision and mutation identity checks.',
  ),
  invoke(
    'editor-tab-reopen',
    'editor-tab-reopen',
    'EditorWorkspaceSynchronizer / tab controls',
    'editorWorkspaceService.reopenEditorTab',
    'registerEditorWorkspaceIPC',
    'VersionedEditorTabMutationInput',
    'EditorTabMutationResult',
    'available',
    'Reopens a closed tab with revision and mutation identity checks.',
  ),
  invoke(
    'editor-tab-delete',
    'editor-tab-delete',
    'EditorWorkspaceSynchronizer / tab controls',
    'editorWorkspaceService.deleteEditorTab',
    'registerEditorWorkspaceIPC',
    'VersionedEditorTabMutationInput',
    'EditorTabMutationResult',
    'available',
    'Marks a tab deleted while retaining versioned mutation history.',
  ),
  invoke(
    'editor-active-tab-set',
    'editor-workspace-set-active',
    'EditorWorkspaceSynchronizer / editorStore',
    'editorWorkspaceService.setActiveEditorTab',
    'registerEditorWorkspaceIPC',
    '{ workspaceId, tabId }',
    'SetActiveEditorTabResult',
    'available',
    'Persists the active tab for workspace restoration.',
  ),

  // Desktop pets
  invoke(
    'pet-list',
    'pets-list',
    'AI pet controls',
    'pets.listInstalledPets',
    'registerPetsIPC',
    'none',
    'CodexPetDefinition[]',
    'available',
    'Lists built-in and locally installed pet manifests.',
  ),
  invoke(
    'pet-install-slug',
    'pets-install-slug',
    'AI pet controls',
    'pets.installPetBySlug',
    'registerPetsIPC',
    'slug: string',
    'PetInstallResult',
    'requires-environment',
    'Downloads a validated pet package and therefore requires network access.',
  ),
  invoke(
    'pet-import-file',
    'pets-import-file',
    'AI pet controls',
    'pets.importPetFromFile',
    'registerPetsIPC',
    'none (native file dialog)',
    'PetInstallResult',
    'available',
    'Imports a local pet archive selected by the user.',
  ),
  invoke(
    'pet-import-directory',
    'pets-import-directory',
    'AI pet controls',
    'pets.selectPetDirectory',
    'registerPetsIPC',
    'none (native directory dialog)',
    'PetInstallResult',
    'available',
    'Imports a local pet directory selected by the user.',
  ),

  // Destructive settings action
  invoke(
    'learning-records-clear',
    'learning-records-clear',
    'SettingsView',
    'settingsService.clearLearningRecords',
    'registerLearningRecordsIPC',
    'none',
    'LearningRecordsClearResult',
    'available',
    'Clears learning records transactionally while preserving app configuration and content.',
  ),

  // Main-to-renderer events
  event(
    'app-close-flush-request',
    'app-before-close',
    'App',
    'appCloseLifecycle.bindAppCloseLifecycle',
    'electron/main.ts',
    '{ requestId }',
    'void callback followed by app-close-flush-complete',
    'available',
    'Sent before BrowserWindow closes so editor and practice data can finish bounded persistence.',
  ),
  event(
    'ai-chat-stream-chunk',
    'ai-chat-chunk',
    'ChatView / chatStore',
    'aiService.onChunk',
    'registerAIIPC',
    '{ requestId, chunk }',
    'void callback',
    'requires-environment',
    'Emitted only while a configured provider stream is active.',
  ),
  event(
    'ai-chat-stream-complete',
    'ai-chat-done',
    'ChatView / chatStore',
    'aiService.onDone',
    'registerAIIPC',
    '{ requestId, content }',
    'void callback',
    'requires-environment',
    'Emitted when a configured provider stream completes.',
  ),
  event(
    'editor-workspace-change-notification',
    'editor-workspace-changed',
    'EditorWorkspaceSynchronizer',
    'editorWorkspaceService.onEditorWorkspaceChanged',
    'registerEditorWorkspaceIPC',
    'EditorWorkspaceChangedEvent',
    'void callback',
    'available',
    'Notifies other renderer consumers after versioned tab or view-state mutations.',
  ),
]
