/**
 * Shared type definitions for the Knowledge module.
 *
 * These interfaces are the single source of truth for knowledge-base related
 * data structures used across stores, views, and IPC calls.
 */

/** A document uploaded to the knowledge base. */
export interface Document {
  id: number
  filename: string
  file_type: string
  chunk_count: number
  created_at: string
  /** Auto-generated or user-assigned tags (comma-separated in storage). */
  tags?: string
}

/** A chunk of text from a knowledge base document. */
export interface Chunk {
  id: number
  document_id: number
  content: string
  chunk_index: number
}

/** A single search result from the knowledge base. */
export interface SearchResult {
  content: string
  filename: string
  score: number
  /** AI-generated relevance explanation (populated by semantic search). */
  explanation?: string
  /** Document ID for cross-referencing. */
  doc_id?: number
  /** Chunk ID for precise referencing. */
  chunk_id?: number
}

// ---------------------------------------------------------------------------
// Semantic Search
// ---------------------------------------------------------------------------

/** Result from an AI-powered semantic search. */
export interface SemanticSearchResult {
  content: string
  filename: string
  doc_id: number
  chunk_id: number
  /** Semantic similarity score (0..1). */
  score: number
  /** Brief AI explanation of why this result is relevant. */
  explanation: string
}

/** AI-generated summary of a set of search results. */
export interface SearchSummary {
  /** Concise summary synthesizing the key findings. */
  summary: string
  /** Key concepts or topics identified across the results. */
  keyConcepts: string[]
}

// ---------------------------------------------------------------------------
// Knowledge Graph
// ---------------------------------------------------------------------------

/** A node in the knowledge concept graph. */
export interface ConceptNode {
  /** Unique identifier (typically the concept name slugified). */
  id: string
  /** Display label for the concept. */
  label: string
  /** Number of related documents/chunks. */
  weight: number
  /** Category grouping (e.g. "algorithm", "data-structure"). */
  category: string
}

/** An edge connecting two concept nodes. */
export interface ConceptEdge {
  /** Source concept node ID. */
  source: string
  /** Target concept node ID. */
  target: string
  /** Strength of the relationship (0..1). */
  weight: number
  /** Optional label describing the relationship. */
  label?: string
}

/** The full concept graph structure. */
export interface ConceptGraph {
  nodes: ConceptNode[]
  edges: ConceptEdge[]
}

/** Detailed drill-down information for a single concept. */
export interface ConceptDetail {
  concept: ConceptNode
  /** Related document filenames. */
  documents: string[]
  /** Related concept IDs. */
  relatedConcepts: string[]
  /** AI-generated description of the concept. */
  description: string
}

// ---------------------------------------------------------------------------
// Auto-Tagger
// ---------------------------------------------------------------------------

/** A tag with metadata. */
export interface Tag {
  /** Unique tag identifier. */
  id: number
  /** Display name. */
  name: string
  /** Number of documents carrying this tag. */
  count: number
  /** Optional color for visual distinction. */
  color?: string
}

/** Suggested tags for a document generated by AI. */
export interface TagSuggestion {
  /** Tag name. */
  tag: string
  /** AI confidence in this suggestion (0..1). */
  confidence: number
  /** Brief reason for the suggestion. */
  reason: string
}

// ---------------------------------------------------------------------------
// RAG Context Awareness
// ---------------------------------------------------------------------------

/** A recent problem the user has been working on. */
export interface RecentProblem {
  id: number
  title: string
  difficulty: string
  tags: string
  /** Whether the user solved it. */
  solved: boolean
  /** When the user last interacted with it. */
  lastActivity: string
}

/** A learning history entry. */
export interface LearningEntry {
  /** Topic or concept name. */
  topic: string
  /** Summary of what was learned/encountered. */
  summary: string
  /** When this entry was created. */
  timestamp: string
  /** Source (e.g. "chat", "problem", "knowledge"). */
  source: string
}

/** Assembled context payload for RAG queries. */
export interface RAGContext {
  /** Recent problems the user has worked on. */
  recentProblems: RecentProblem[]
  /** User learning history entries. */
  learningHistory: LearningEntry[]
  /** Relevant knowledge base chunks. */
  knowledgeChunks: string[]
  /** User-specific preferences or skill level hints. */
  userProfile: {
    preferredLanguage: string
    difficultyLevel: string
    strongTopics: string[]
    weakTopics: string[]
  }
}
